// src/components/Chat/SellerMultiStepForm.tsx
import { useState, useEffect } from "react";
import { useForm } from "react-hook-form";
import { Loader2, CheckCircle, Download, FileText, Wallet } from "lucide-react";
import type { SellerApproval, BuyerRequest } from "../../types/chat.types";
import api from "../../api/axios";
import SummaryApi from "../../api/SummaryApi";

interface SellerMultiStepFormProps {
  tradeId: string;
  buyerRequest: BuyerRequest;
  onApprove: (data: SellerApproval) => void;
  onReject: () => void;
}

type FormValues = {
  // VTR confirmation
  vtrGenerated: boolean;

  // Conditional Logic First Buy
  conditionalLogicConfirmed: boolean;

  // SCNDA Draft
  scndaSigned: boolean;

  // Escrow details
  transferMethod: string;
  walletAddress?: string;
  txnHash?: string;
};

export default function SellerMultiStepForm({
  tradeId,
  buyerRequest,
  onApprove,
  onReject,
}: SellerMultiStepFormProps) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isChatLoading, setIsChatLoading] = useState(true);
  const [chatError, setChatError] = useState<string | null>(null);
  const [chatData, setChatData] = useState<any>(null);

  // Document generation states
  const [vtrDocument, setVtrDocument] = useState<string | null>(null);
  const [scndaDocument, setScndaDocument] = useState<string | null>(null);
  const [escrowConfirmation, setEscrowConfirmation] = useState<string | null>(null);

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<FormValues>({
    defaultValues: {
      vtrGenerated: false,
      conditionalLogicConfirmed: false,
      scndaSigned: false,
      transferMethod: "wallet",
      walletAddress: "",
      txnHash: "",
    },
  });

  useEffect(() => {
    if (!tradeId) {
      setIsChatLoading(false);
      setChatError("Missing tradeId, cannot fetch chat details.");
      return;
    }

    let cancelled = false;

    const fetchChatByTrade = async () => {
      try {
        setIsChatLoading(true);
        setChatError(null);

        const chatConfig = SummaryApi.getChatByTradeId(tradeId);
        const chatRes = await api({
          url: chatConfig.url,
          method: chatConfig.method,
        });

        const payload = chatRes.data?.data || chatRes.data;
        if (cancelled) return;

        console.log("getChatByTradeId response:", payload);
        setChatData(payload);
      } catch (err: any) {
        if (cancelled) return;
        console.error("Failed to fetch chat by trade:", err);
        setChatError(
          err?.response?.data?.message ||
            err?.message ||
            "Failed to fetch chat details"
        );
      } finally {
        if (!cancelled) setIsChatLoading(false);
      }
    };

    fetchChatByTrade();

    return () => {
      cancelled = true;
    };
  }, [tradeId]);

  const trade =
    chatData?.chat?.tradeId || chatData?.tradeId || chatData?.trade || null;

  // Remove unused fee variable or use it
  // const fee = trade?.feeBreakdown || {}; // This was unused
  
  // Use fee data if needed elsewhere, or remove completely
  //const feeBreakdown = trade?.feeBreakdown || {}; // Optional: Rename and keep if needed
  
  const cryptoAmount = trade?.cryptoAmount ?? buyerRequest.usdtAmount;
  const totalINRAmount = trade?.totalINRAmount ?? buyerRequest.inrAmount;
  const escrowWalletAddress = trade?.escrowWalletAddress;

  // Calculate fees
  const cryptiansFee = cryptoAmount * 0.04;
  const totalFee = cryptiansFee;
  const depositToEscrow = cryptoAmount + totalFee;

  // Generate VTR Document
  const handleGenerateVTR = () => {
    const vtrContent = `
VERIFIABLE TRADE RECEIPT (VTR)

Trade ID: ${tradeId}
Date: ${new Date().toLocaleDateString()}

TRANSACTION DETAILS:
- Crypto Amount: ${cryptoAmount} USDT
- INR Amount: ₹${totalINRAmount}
- Escrow Address: ${escrowWalletAddress || "Pending"}

SELLER OBLIGATIONS:
- Deposit ${depositToEscrow.toFixed(2)} USDT to escrow
- Confirm buyer's payment receipt
- Release crypto upon verification

BUYER OBLIGATIONS:
- Transfer ₹${totalINRAmount} to seller
- Provide payment proof (UTR)
- Provide valid wallet address

This receipt serves as proof of trade initiation and obligations.

---
Generated by Cryptians Platform
    `.trim();

    const blob = new Blob([vtrContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    setVtrDocument(url);
  };

  // Generate SCNDA Document
  const handleGenerateSCNDA = () => {
    const scndaContent = `
SELLER CIRCUMVENTION NON-DISCLOSURE AGREEMENT (SCNDA)

Trade ID: ${tradeId}
Effective Date: ${new Date().toLocaleDateString()}

This Agreement is entered into by and between:
SELLER: [Seller Name]
BUYER: [Buyer Name]

1. NON-CIRCUMVENTION
The Seller agrees not to circumvent, avoid, or bypass the Buyer in any transaction related to this trade.

2. NON-DISCLOSURE
All information shared during this trade shall remain confidential and not be disclosed to third parties.

3. TERM
This agreement remains in effect for the duration of the trade and 12 months thereafter.

4. GOVERNING LAW
This agreement shall be governed by applicable laws.

SELLER SIGNATURE: ___________________
DATE: ${new Date().toLocaleDateString()}

---
Generated by Cryptians Platform
    `.trim();

    const blob = new Blob([scndaContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    setScndaDocument(url);
  };

  // Generate Escrow Confirmation
  const handleGenerateEscrowConfirmation = () => {
    const confirmationContent = `
CONDITIONAL LOGIC - FIRST BUY CONFIRMATION

Trade ID: ${tradeId}
Date: ${new Date().toLocaleDateString()}

ESCROW DETAILS:
- Escrow Wallet: ${escrowWalletAddress || "Pending"}
- Amount to Deposit: ${depositToEscrow.toFixed(2)} USDT
- Crypto Amount: ${cryptoAmount} USDT
- Platform Fee (4%): ${cryptiansFee.toFixed(2)} USDT

CONDITIONAL TERMS:
✓ Seller must deposit crypto to escrow before buyer makes payment
✓ Admin will verify the deposit before buyer proceeds
✓ Buyer will transfer INR only after admin confirmation
✓ Crypto will be released only after seller confirms INR receipt

CONFIRMATION:
By signing this, the seller confirms understanding of the escrow process and agrees to deposit the required amount.

SELLER CONFIRMATION: YES
DATE: ${new Date().toLocaleDateString()}

---
Generated by Cryptians Platform
    `.trim();

    const blob = new Blob([confirmationContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    setEscrowConfirmation(url);
  };

  const onFormSubmit = async (formData: FormValues) => {
    if (!formData.txnHash || !formData.txnHash.trim()) {
      alert("Transaction hash is required before submitting.");
      return;
    }

    setIsSubmitting(true);

    try {
      // Submit deposit hash to backend
      const depositConfig = SummaryApi.submitDepositeHash(
        tradeId,
        formData.txnHash.trim()
      );

      await api({
        url: depositConfig.url,
        method: depositConfig.method,
        data: depositConfig.data,
      });

      // Build approval object
      const approval: SellerApproval = {
        approved: true,
        usdtToEscrow: depositToEscrow,
        walletAddress: formData.walletAddress,
        txnHash: formData.txnHash.trim(),
        feeDetails: {
          usdtAmount: cryptoAmount,
          cryptiansFee,
          totalFee,
        },
      };

      onApprove(approval);
    } catch (err: any) {
      console.error("Error submitting deposit hash:", err);
      const msg =
        err?.response?.data?.message ||
        err?.message ||
        "Failed to submit deposit. Please try again.";
      alert(msg);
    } finally {
      setIsSubmitting(false);
    }
  };

  if (isChatLoading) {
    return (
      <div className="bg-white rounded-2xl shadow-lg p-6 max-w-2xl mx-auto my-4 border-2 border-green-500 flex items-center justify-center gap-2">
        <Loader2 className="w-5 h-5 animate-spin" />
        <span className="text-sm text-gray-700">Loading trade details...</span>
      </div>
    );
  }

  if (chatError) {
    return (
      <div className="bg-white rounded-2xl shadow-lg p-6 max-w-2xl mx-auto my-4 border-2 border-red-500">
        <p className="text-red-700 text-sm mb-4">{chatError}</p>
        <button
          onClick={onReject}
          className="px-4 py-2 bg-red-100 text-red-700 rounded-lg font-semibold hover:bg-red-200"
        >
          Close
        </button>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-2xl shadow-lg p-6 max-w-3xl mx-auto my-4 border-2 border-green-500">
      <div className="flex items-center gap-3 mb-4">
        <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center">
          <CheckCircle className="w-6 h-6 text-green-600" />
        </div>
        <div>
          <h3 className="text-xl font-bold text-gray-900">
            Seller Approval Form
          </h3>
          <p className="text-sm text-gray-600">
            Review documents and approve buyer request
          </p>
        </div>
      </div>

      {/* Buyer Request Summary */}
      <div className="bg-gray-50 rounded-lg p-4 mb-4 border border-gray-200">
        <h4 className="font-semibold text-gray-900 mb-3">Buyer Requested:</h4>
        <div className="space-y-2 text-sm">
          <div className="flex justify-between">
            <span className="text-gray-600">USDT Amount:</span>
            <span className="font-semibold">{cryptoAmount} USDT</span>
          </div>
          <div className="flex justify-between">
            <span className="text-gray-600">INR You Receive:</span>
            <span className="font-semibold text-green-600">
              ₹{Number(totalINRAmount || 0).toFixed(2)}
            </span>
          </div>
        </div>
      </div>

      {/* Deposit Details */}
      <div className="bg-green-50 rounded-lg p-4 mb-4 border border-green-200">
        <h4 className="font-semibold text-gray-900 mb-3">Deposit to Escrow:</h4>
        <div className="space-y-2 text-sm">
          <div className="flex justify-between">
            <span className="text-gray-600">USDT Amount:</span>
            <span className="font-semibold">{cryptoAmount} USDT</span>
          </div>
          <div className="flex justify-between">
            <span className="text-gray-600">Cryptians Fee (4%):</span>
            <span className="font-semibold">{cryptiansFee.toFixed(2)} USDT</span>
          </div>
          <div className="border-t border-green-300 pt-2 mt-2 flex justify-between">
            <span className="font-bold text-gray-900">Total Deposit:</span>
            <span className="font-bold text-green-600 text-lg">
              {depositToEscrow.toFixed(2)} USDT
            </span>
          </div>
          {escrowWalletAddress && (
            <div className="mt-2">
              <span className="text-gray-600 block mb-1 text-xs">
                Escrow Wallet Address:
              </span>
              <span className="font-mono text-xs break-all bg-white p-2 rounded border">
                {escrowWalletAddress}
              </span>
            </div>
          )}
        </div>
      </div>

      <form onSubmit={handleSubmit(onFormSubmit)} className="space-y-4">
        {/* Form 1: VTR */}
        <div className="border-2 border-blue-200 rounded-lg p-4">
          <h4 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
            <FileText className="w-5 h-5 text-blue-600" />
            Step 1: VTR (Verifiable Trade Receipt)
          </h4>

          <div className="space-y-3">
            <p className="text-sm text-gray-600">
              Generate and review the Verifiable Trade Receipt for this transaction.
            </p>

            <button
              type="button"
              onClick={handleGenerateVTR}
              className="w-full px-4 py-2 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 flex items-center justify-center gap-2"
            >
              <FileText className="w-4 h-4" />
              Generate VTR
            </button>

            {vtrDocument && (
              <a
                href={vtrDocument}
                download={`VTR_${tradeId}.txt`}
                className="w-full px-4 py-2 bg-green-100 text-green-700 rounded-lg font-semibold hover:bg-green-200 flex items-center justify-center gap-2 border border-green-300"
              >
                <Download className="w-4 h-4" />
                Download VTR
              </a>
            )}

            <label className="flex items-start gap-3 p-3 border rounded-lg cursor-pointer hover:bg-gray-50">
              <input
                type="checkbox"
                {...register("vtrGenerated", {
                  required: "You must confirm VTR generation",
                })}
                className="w-5 h-5 text-blue-600 mt-0.5"
              />
              <span className="text-sm">
                I have generated and reviewed the VTR document
              </span>
            </label>
            {errors.vtrGenerated && (
              <span className="text-red-600 text-sm">
                {errors.vtrGenerated.message}
              </span>
            )}
          </div>
        </div>

        {/* Conditional Logic - First Buy */}
        <div className="border-2 border-purple-200 rounded-lg p-4">
          <h4 className="font-semibold text-gray-900 mb-3">
            Step 2: Conditional Logic - First Buy Confirmation
          </h4>

          <div className="space-y-3">
            <p className="text-sm text-gray-600">
              Review and confirm the escrow conditions before proceeding.
            </p>

            <button
              type="button"
              onClick={handleGenerateEscrowConfirmation}
              className="w-full px-4 py-2 bg-purple-600 text-white rounded-lg font-semibold hover:bg-purple-700 flex items-center justify-center gap-2"
            >
              <FileText className="w-4 h-4" />
              Generate Confirmation
            </button>

            {escrowConfirmation && (
              <a
                href={escrowConfirmation}
                download={`EscrowConfirmation_${tradeId}.txt`}
                className="w-full px-4 py-2 bg-green-100 text-green-700 rounded-lg font-semibold hover:bg-green-200 flex items-center justify-center gap-2 border border-green-300"
              >
                <Download className="w-4 h-4" />
                Download Confirmation
              </a>
            )}

            <label className="flex items-start gap-3 p-3 border rounded-lg cursor-pointer hover:bg-gray-50">
              <input
                type="checkbox"
                {...register("conditionalLogicConfirmed", {
                  required: "You must confirm the conditional logic",
                })}
                className="w-5 h-5 text-purple-600 mt-0.5"
              />
              <span className="text-sm">
                I understand and accept the conditional logic and first buy terms
              </span>
            </label>
            {errors.conditionalLogicConfirmed && (
              <span className="text-red-600 text-sm">
                {errors.conditionalLogicConfirmed.message}
              </span>
            )}
          </div>
        </div>

        {/* SCNDA Draft */}
        <div className="border-2 border-orange-200 rounded-lg p-4">
          <h4 className="font-semibold text-gray-900 mb-3">
            Step 3: SCNDA Draft (Seller Circumvention Non-Disclosure Agreement)
          </h4>

          <div className="space-y-3">
            <p className="text-sm text-gray-600">
              Generate and sign the SCNDA to proceed with the trade.
            </p>

            <button
              type="button"
              onClick={handleGenerateSCNDA}
              className="w-full px-4 py-2 bg-orange-600 text-white rounded-lg font-semibold hover:bg-orange-700 flex items-center justify-center gap-2"
            >
              <FileText className="w-4 h-4" />
              Generate SCNDA
            </button>

            {scndaDocument && (
              <a
                href={scndaDocument}
                download={`SCNDA_${tradeId}.txt`}
                className="w-full px-4 py-2 bg-green-100 text-green-700 rounded-lg font-semibold hover:bg-green-200 flex items-center justify-center gap-2 border border-green-300"
              >
                <Download className="w-4 h-4" />
                Download SCNDA
              </a>
            )}

            <label className="flex items-start gap-3 p-3 border rounded-lg cursor-pointer hover:bg-gray-50">
              <input
                type="checkbox"
                {...register("scndaSigned", {
                  required: "You must sign the SCNDA",
                })}
                className="w-5 h-5 text-orange-600 mt-0.5"
              />
              <span className="text-sm">
                I have read, understood, and agree to the SCNDA terms
              </span>
            </label>
            {errors.scndaSigned && (
              <span className="text-red-600 text-sm">
                {errors.scndaSigned.message}
              </span>
            )}
          </div>
        </div>

        {/* Crypto Transfer Section */}
        <div className="border-2 border-green-200 rounded-lg p-4">
          <h4 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
            <Wallet className="w-5 h-5 text-green-600" />
            Step 4: Crypto Transfer to Escrow
          </h4>

          <div className="space-y-3">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Transfer Method *
              </label>
              <select
                {...register("transferMethod", { required: true })}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500"
              >
                <option value="wallet">Transfer to Wallet</option>
                <option value="connect">Connect Wallet to Pay Directly</option>
              </select>
            </div>

            {watch("transferMethod") === "wallet" && (
              <>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Your Wallet Address (Optional)
                  </label>
                  <input
                    type="text"
                    {...register("walletAddress")}
                    className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500"
                    placeholder="0x..."
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Transaction Hash *
                  </label>
                  <input
                    type="text"
                    {...register("txnHash", {
                      required: watch("transferMethod") === "wallet",
                    })}
                    className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500"
                    placeholder="Enter transaction hash"
                  />
                  {errors.txnHash && (
                    <span className="text-red-600 text-sm">
                      Transaction hash is required
                    </span>
                  )}
                </div>
              </>
            )}
          </div>
        </div>

        {/* Actions */}
        <div className="flex gap-3 pt-4 border-t">
          <button
            type="button"
            onClick={onReject}
            className="flex-1 px-4 py-3 bg-red-100 text-red-700 rounded-lg font-semibold hover:bg-red-200"
            disabled={isSubmitting}
          >
            Reject Request
          </button>
          <button
            type="submit"
            disabled={isSubmitting}
            className="flex-1 px-4 py-3 bg-gradient-to-r from-green-600 to-emerald-600 text-white rounded-lg font-semibold hover:shadow-lg disabled:opacity-50 flex items-center justify-center gap-2"
          >
            {isSubmitting ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                Processing...
              </>
            ) : (
              <>
                <Wallet className="w-5 h-5" />
                Approve & Transfer Crypto
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  );
}